is:
#  - headers.acceptJson
#  - headers.testScenarioHeader
  - errors.formatNino
  - errors.invalidCredentials
  - errors.clientOrAgentNotAuthorisedAcknowledge
  - errors.reportNotFound

displayName: Acknowledge a HMRC Assist Report
description: This endpoint allows a developer to acknowledge that the specified report has been read by either the taxpayer or agent.
#(annotations.sandboxData): !include ../../scenarios/selfAssessment/retrieveIncomeTaxAndNics.md
(annotations.scope): "write:self-assessment-assist"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment-assist" ] } ]
responses:
  204:
  500:
